"""initial_schema

Revision ID: 218a8381d0c8
Revises: 
Create Date: 2026-02-21 06:48:37.508772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '218a8381d0c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insurer_code', sa.String(length=50), nullable=False),
    sa.Column('insurer_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('steps_completed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_insurer_code'), 'pipeline_runs', ['insurer_code'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('pipeline_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('detected_format', sa.String(length=50), nullable=True),
    sa.Column('s3_key', sa.String(length=1000), nullable=True),
    sa.Column('local_path', sa.String(length=1000), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_files_role'), 'pipeline_files', ['role'], unique=False)
    op.create_index(op.f('ix_pipeline_files_run_id'), 'pipeline_files', ['run_id'], unique=False)
    op.create_table('pipeline_step_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('step_description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_step_logs_run_id'), 'pipeline_step_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_step_logs_status'), 'pipeline_step_logs', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_step_logs_step_name'), 'pipeline_step_logs', ['step_name'], unique=False)
    op.create_table('pipeline_extracted_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('source_role', sa.String(length=100), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['pipeline_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_extracted_data_file_id'), 'pipeline_extracted_data', ['file_id'], unique=False)
    op.create_index(op.f('ix_pipeline_extracted_data_run_id'), 'pipeline_extracted_data', ['run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_extracted_data_source_role'), 'pipeline_extracted_data', ['source_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_extracted_data_source_role'), table_name='pipeline_extracted_data')
    op.drop_index(op.f('ix_pipeline_extracted_data_run_id'), table_name='pipeline_extracted_data')
    op.drop_index(op.f('ix_pipeline_extracted_data_file_id'), table_name='pipeline_extracted_data')
    op.drop_table('pipeline_extracted_data')
    op.drop_index(op.f('ix_pipeline_step_logs_step_name'), table_name='pipeline_step_logs')
    op.drop_index(op.f('ix_pipeline_step_logs_status'), table_name='pipeline_step_logs')
    op.drop_index(op.f('ix_pipeline_step_logs_run_id'), table_name='pipeline_step_logs')
    op.drop_table('pipeline_step_logs')
    op.drop_index(op.f('ix_pipeline_files_run_id'), table_name='pipeline_files')
    op.drop_index(op.f('ix_pipeline_files_role'), table_name='pipeline_files')
    op.drop_table('pipeline_files')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_insurer_code'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
