"""add_started_at_index

Revision ID: 53b824318ebe
Revises: 218a8381d0c8
Create Date: 2026-02-21 07:08:27.071159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b824318ebe'
down_revision: Union[str, None] = '218a8381d0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pipeline_runs_started_at'), 'pipeline_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_started_at'), table_name='pipeline_runs')
    # ### end Alembic commands ###
