"""add_output_column_to_step_logs

Revision ID: 6d39ed79a600
Revises: 53b824318ebe
Create Date: 2026-02-22 16:00:46.077832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d39ed79a600'
down_revision: Union[str, None] = '53b824318ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_step_logs', sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_step_logs', 'output')
    # ### end Alembic commands ###
